use Station

delete from Betten

SET IDENTITY_INSERT Betten ON

insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (1, 1, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (2, 1, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (3, 1, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (4, 2, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (5, 2, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (6, 2, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (7, 3, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (8, 3, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (9, 3, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (10, 4, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (11, 4, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (12, 4, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (13, 5, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (14, 5, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (15, 5, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (16, 6, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (17, 6, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (18, 6, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (19, 7, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (20, 7, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (21, 7, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (22, 8, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (23, 8, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (24, 8, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (25, 9, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (26, 9, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (27, 9, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (28, 10, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (29, 10, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (30, 10, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (31, 11, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (32, 11, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (33, 11, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (34, 12, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (35, 12, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (36, 12, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (37, 13, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (38, 13, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (39, 13, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (40, 14, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (41, 14, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (42, 14, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (43, 15, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (44, 15, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (45, 15, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (46, 16, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (47, 16, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (48, 16, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (49, 17, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (50, 17, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (51, 17, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (52, 18, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (53, 18, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (54, 18, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (55, 19, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (56, 19, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (57, 19, 3)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (58, 20, 1)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (59, 20, 2)
insert into Betten (ID_Betten, ID_Zimmer, Nummer) values (60, 20, 3)

SET IDENTITY_INSERT Betten OFF
